#!/usr/bin/env python3

# TODO

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored


def main():

    # ensure proper usage
    if len(sys.argv) != 2 or sys.argv[1][0] != "@":
        sys.exit("Usage: ./tweet @screen_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")


    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get_user_tweets
    screen_name = sys.argv[1].lstrip("@")
    # check for the account is available or not
    string = helpers.get_user_timeline(screen_name,50)
    if string == None:
        sys.exit("No right to access this account, try another one.")
    
    # analyze word
    for tweet in string:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(score, "green"), " ", colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "red"), " ", colored(tweet, "red"))
        else:
            print(colored(score, "yellow"), " ", colored(tweet, "yellow"))
if __name__ == "__main__":
    main()

